import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PlausibleProvider from "next-plausible";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PlausibleProvider
        domain={process.env.NEXT_PUBLIC_FRONTEND_DOMAIN!}
        selfHosted={true}
        enabled={true}
        trackLocalhost={true}
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
